### PR TITLE
SaveableStateHolder remove state for destroyed elements

### LINKED ISSUE #375: SaveableStateRegistry overflow causes TransactionTooLargeException
How to reproduce:

1. Using sample sanbox app, setup https://github.com/guardian/toolargetool tool
2. Enable "Don't keep activities" in dev settings
3. Minimize app, look at logcat. `androidx.lifecycle.BundlableSavedStateRegistry.key` takes `3.6 KB` 
4. In sanbox navigate back and forth to NavModel Examples
5. Minimize app again, now `androidx.lifecycle.BundlableSavedStateRegistry.key` takes much more than `3.6 KB` 

What's wrong:
If you'll take a look into saved bundle, you can see that even disposed Nodes still keeps some of their data in saved state registry
Thus, more we navigates through the app, more garbage collected in `SavedStateRegistry`, and at some point it causes `TransactionTooLargeException` after app pausing

You can find saved `NavKeys` and some data in output bundle using debugger:
`(outputBundle.getBundle("androidx.lifecycle.BundlableSavedStateRegistry.key").get("SaveableStateRegistry:-1") as BaseBundle)`
Than `mMap -> values[0] -> [0]`

My assumption what's wrong (i might be way off):
Appyx registers `SaveableStateProvider` https://github.com/bumble-tech/appyx/blob/1.x/libraries/core/src/main/kotlin/com/bumble/appyx/core/composable/Child.kt#L46 but never unregisters it, neither Compose does

Want to notice that in sample app overhead after each navigation isn't that big, but in my app (may be because of NavTarget data size) each navigation takes much more memory

### PR DESCRIPTION
**Pull request by KovalevAndrey**
## Description

Fixes https://github.com/bumble-tech/appyx/issues/375

Remove saveableStateHolder state for destroyed elements

## Check list

- [x] I have updated `CHANGELOG.md` if required.
- [x] I have updated documentation if required.

### CODE REVIEW

File: libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/NavModelExt.kt [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+import com.bumble.appyx.core.withPrevious
+import kotlinx.coroutines.flow.map
+
+fun <NavTarget, State> NavModel<NavTarget, State>.removedElementKeys() =
+    this
+        .elements
+        .withPrevious()
+        .map { values ->
+            val previousKeys = values.previous?.map { it.key }
```
Comment (CherryPerry) [inline libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/NavModelExt.kt]: `?.map { }.orEmpty()` instead of null check.

Comment (CherryPerry) [reply libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/NavModelExt.kt]: You can also use `mapTo(HashSet()) {}`. Then you can subtract one set from another to find delta between them (check child node manager).

File: libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/NavModelExt.kt [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+            val currentKeys = values.current.map { it.key }
+            if (previousKeys == null) {
+                emptyList()
+            } else {
+                val deletedElements = mutableListOf<NavKey<NavTarget>>()
+                previousKeys.forEach { element ->
+                    if (currentKeys.contains(element).not()) {
```
Comment (CherryPerry) [inline libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/NavModelExt.kt]: Please, do not use `.not()`

File: libraries/core/src/main/kotlin/com/bumble/appyx/core/composable/Children.kt [hunk 3]
```diff
@@ -123,6 +125,22 @@ class ChildrenTransitionScope<T : Any, S>(
...
     ) {
+        val saveableStateHolder = rememberSaveableStateHolder()
+
+        val removedElementsFlow = remember {
+            navModel.removedElementKeys().map { list ->
+                list
+                    .filter { clazz.isInstance(it.navTarget) }
+            }
+        }
+        LaunchedEffect(this@ChildrenTransitionScope) {
```
Comment (CherryPerry) [inline libraries/core/src/main/kotlin/com/bumble/appyx/core/composable/Children.kt]: Why `ChildrenTransitionScope` here and not `navModel`?
Probably we can move flow creating here because it will be invoked almost only once (`navModel` won't change).

File: libraries/core/src/main/kotlin/com/bumble/appyx/core/composable/Children.kt [hunk 4]
```diff
@@ -123,6 +125,22 @@ class ChildrenTransitionScope<T : Any, S>(
...
+            removedElementsFlow.collect { deletedElements ->
+                deletedElements.forEach { navKey ->
+                    saveableStateHolder.removeState(navKey)
```
Comment (CherryPerry) [inline libraries/core/src/main/kotlin/com/bumble/appyx/core/composable/Children.kt]: A little sad to see that we have 2 different places to control it (set key in `Child` and remove key in `Children`), but I can't propose anything better.

File: libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/NavModelExt.kt [hunk 5]
```diff
@@ -0,0 +1,24 @@
+package com.bumble.appyx.core.navigation
+
+import com.bumble.appyx.core.withPrevious
+import kotlinx.coroutines.flow.map
+
+fun <NavTarget, State> NavModel<NavTarget, State>.removedElementKeys() =
```
Comment (CherryPerry) [inline libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/NavModelExt.kt]: Make `internal`.

File: libraries/core/src/main/kotlin/com/bumble/appyx/core/composable/Children.kt (hunk 4 above)
Comment (KovalevAndrey) [reply libraries/core/src/main/kotlin/com/bumble/appyx/core/composable/Children.kt]: > A little sad to see that we have 2 different places to control it (set key in `Child` and remove key in `Children`), but I can't propose anything better.

Yes, in order not to introduce breaking change we have to do it in 2 places

File: libraries/core/src/main/kotlin/com/bumble/appyx/core/composable/Children.kt (hunk 3 above)
Comment (KovalevAndrey) [reply libraries/core/src/main/kotlin/com/bumble/appyx/core/composable/Children.kt]: moved

File: libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/NavModelExt.kt (hunk 1 above)
Comment (KovalevAndrey) [reply libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/NavModelExt.kt]: simplified it but in a different way

**Review by CherryPerry — APPROVED** [review]
